version: 2.0

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: /home/circleci/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Notify slack
          command: |
            VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7)
            curl -X POST --data-urlencode "payload={\"channel\": \"#robots\", \"text\": \"Starting Atlas release: $VERSION\"}" https://hooks.slack.com/services/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
      - run:
          name: Build Docker image
          command: |
            VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7)
            docker build -t gcr.io/$GCP_PROJECT_ID/pheme-atlas:$VERSION -t gcr.io/$GCP_PROJECT_ID/pheme-atlas:latest .
      - run:
          name: Setup gcloud auth
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GCP_PROJECT_ID}
      - run:
          name: Push Docker image
          command: |
            VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7)
            gcloud -q auth configure-docker
            docker push gcr.io/$GCP_PROJECT_ID/pheme-atlas:$VERSION
            docker push gcr.io/$GCP_PROJECT_ID/pheme-atlas:latest
      - run:
          name: Deploy new image to the atlas GCP instance
          command: |
            VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7)
            gcloud compute instances update-container pheme-atlas-mainnet --container-image gcr.io/$GCP_PROJECT_ID/pheme-atlas:$VERSION
      - run:
          name: Notify slack about the deployment
          command: |
            VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7)
            curl -X POST --data-urlencode "payload={\"channel\": \"#robots\", \"text\": \"Finished Atlas release: $VERSION\"}" https://hooks.slack.com/services/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

filters: &filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          <<: *filters