name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dcntrlzd/pheme-atlas:$(git rev-parse --short HEAD) --tag dcntrlzd/pheme-atlas:latest

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker Image
      run: docker push dcntrlzd/pheme-atlas:$(git rev-parse --short HEAD)

